menu:
  Blog: /blog/
  Archives: /blog/archives
  Album: /blog/album
  About: /blog/about

widgets: 
- search
- category
- tagcloud

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:
